CREATE DATABASE IF NOT EXISTS SPM;
USE SPM;

CREATE TABLE IF NOT EXISTS projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  owner VARCHAR(255),
  status ENUM('Active','On hold','Archived') NOT NULL DEFAULT 'Active',
  tasks_done INT NOT NULL DEFAULT 0,
  tasks_total INT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);